module GameParams

	CATEGORY_POP = "Pop"
	CATEGORY_SCIENCE = "Science"
	CATEGORY_SPORTS = "Sports"
	CATEGORY_ROCK = "Rock"

	POSITIONS = {
	  "0" => CATEGORY_POP,
	  "1" => CATEGORY_SCIENCE,
	  "2" => CATEGORY_SPORTS, 
	  "3" => CATEGORY_ROCK,
	  "4" => CATEGORY_POP,
	  "5" => CATEGORY_SCIENCE,
	  "6" => CATEGORY_SPORTS,
	  "7" => CATEGORY_ROCK,
	  "8" => CATEGORY_POP,
	  "9" => CATEGORY_SCIENCE,
	  "10" => CATEGORY_SPORTS,
	  "11" => CATEGORY_ROCK
	}

end